application: coaafrica
version: 3
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /apis/.*
  script: api.py  
- url: /static
  static_dir: static
  
builtins:
- datastore_admin: on